<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <ReactiveUIVersion>26.0.1</ReactiveUIVersion>
    <RoslynAnalysersVersion>5.1.2</RoslynAnalysersVersion>
    <ReactiveUIPrimitivesVersion>9.0.0</ReactiveUIPrimitivesVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="CP.Nuke.BuildTools" Version="3.0.2" />
    <PackageVersion Include="log4net" Version="3.5.0" />
    <PackageVersion Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.12.0" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
    <PackageVersion Include="Nuke.Common" Version="10.1.0" />
    <PackageVersion Include="ReactiveUI" Version="$(ReactiveUIVersion)" />
    <PackageVersion Include="ReactiveUI.Reactive" Version="$(ReactiveUIVersion)" />
    <PackageVersion Include="ReactiveUI.WinForms" Version="$(ReactiveUIVersion)" />
    <PackageVersion Include="ReactiveUI.WinForms.Reactive" Version="$(ReactiveUIVersion)" />
    <PackageVersion Include="ReactiveUI.WPF" Version="$(ReactiveUIVersion)" />
    <PackageVersion Include="ReactiveUI.WPF.Reactive" Version="$(ReactiveUIVersion)" />
    <PackageVersion Include="ReactiveUI.Primitives" Version="$(ReactiveUIPrimitivesVersion)" />
    <PackageVersion Include="ReactiveUI.Primitives.Reactive" Version="$(ReactiveUIPrimitivesVersion)" />
    <PackageVersion Include="Roslynator.Analyzers" Version="5.0.1" />
    <PackageVersion Include="StyleSharp.Analyzers" Version="$(RoslynAnalysersVersion)" />
    <PackageVersion Include="PerformanceSharp.Analyzers" Version="$(RoslynAnalysersVersion)" />
    <PackageVersion Include="SecuritySharp.Analyzers" Version="$(RoslynAnalysersVersion)" />
    <PackageVersion Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageVersion Include="System.Management" Version="10.0.12" />
    <PackageVersion Include="System.Resources.Extensions" Version="10.0.12" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.12" />
    <PackageVersion Include="TUnit" Version="1.73.0" />
  </ItemGroup>
</Project>
