// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

#if REACTIVE_SHIM
namespace CP.ReactiveUI.Primitives.Windows.Reactive.Desktop.Input.Structs;
#else
namespace CP.ReactiveUI.Primitives.Windows.Desktop.Input.Structs;
#endif
/// <summary>
/// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
/// See <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/ms646269.aspx">HARDWAREINPUT structure</a>
/// </summary>
public readonly record struct HardwareInput
{
    /// <summary>Gets or sets the message generated by the input hardware.</summary>
    public int UMsg { get; init; }

    /// <summary>Gets or sets the low-order word of the longParameter parameter for uMsg.</summary>
    public short ParamL { get; init; }

    /// <summary>Gets or sets the high-order word of the longParameter parameter for uMsg.</summary>
    public short WParamH { get; init; }
}
