// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

#if REACTIVE_SHIM
namespace CP.ReactiveUI.Primitives.Windows.Reactive.Desktop.Windows.Enums;
#else
namespace CP.ReactiveUI.Primitives.Windows.Desktop.Windows.Enums;
#endif
/// <summary>Used for SetWinEventHook.</summary>
public enum WinEvents : uint
{
    /// <summary>No WinEvent value.</summary>
    None = 0U,
    /// <summary>
    ///     System events
    ///     EVENT_SYSTEM_SOUND
    ///     Sent when a sound is played.  Currently nothing is generating this, we
    ///     this event when a system sound (for menus, etc) is played.  Apps
    ///     generate this, if accessible, when a private sound is played.  For
    ///     example, if Mail plays a "New Mail" sound.
    ///     System Sounds:
    ///     (Generated by PlaySoundEvent in USER itself)
    ///     windowHandle            is NULL
    ///     idObject        is OBJID_SOUND
    ///     idChild         is sound child ID if one
    ///     App Sounds:
    ///     (PlaySoundEvent won't generate notification; up to app)
    ///     windowHandle + idObject gets interface pointer to Sound object
    ///     idChild identifies the sound in question
    ///     are going to be cleaning up the SOUNDSENTRY feature in the control panel
    ///     and will use this at that time.  Applications implementing WinEvents
    ///     are perfectly welcome to use it.  Clients of IAccessible* will simply
    ///     turn around and get back a non-visual object that describes the sound.
    /// </summary>
    EVENT_SYSTEM_SOUND = 1U,
    /// <summary>Represents the EVENT_SYSTEM_ALERT value.</summary>
    EVENT_SYSTEM_ALERT = 2U,
    /// <summary>Represents the EVENT_SYSTEM_FOREGROUND value.</summary>
    EVENT_SYSTEM_FOREGROUND = 3U,
    /// <summary>
    ///     Menu
    ///     windowHandle            is window (top level window or popup menu window)
    ///     idObject        is ID of control (OBJID_MENU, OBJID_SYSMENU, OBJID_SELF for popup)
    ///     idChild         is CHILDID_SELF
    ///     EVENT_SYSTEM_MENUSTART
    ///     EVENT_SYSTEM_MENUEND
    ///     For MENUSTART, windowHandle+idObject+idChild refers to the control with the menu bar,
    ///     or the control bringing up the context menu.
    ///     Sent when entering into and leaving from menu mode (system, app bar, and
    ///     track popups).
    /// </summary>
    EVENT_SYSTEM_MENUSTART = 4U,
    /// <summary>Represents the EVENT_SYSTEM_MENUEND value.</summary>
    EVENT_SYSTEM_MENUEND = 5U,
    /// <summary>
    ///     EVENT_SYSTEM_MENUPOPUPSTART
    ///     EVENT_SYSTEM_MENUPOPUPEND
    ///     Sent when a menu popup comes up and just before it is taken down.  Note
    ///     that for a call to TrackPopupMenu(), a client will see EVENT_SYSTEM_MENUSTART
    ///     followed almost immediately by EVENT_SYSTEM_MENUPOPUPSTART for the popup
    ///     being shown.
    ///     For MENUPOPUP, windowHandle+idObject+idChild refers to the NEW popup coming up, not the
    ///     parent item which is hierarchical.  You can get the parent menu/popup by
    ///     asking for the accParent object.
    /// </summary>
    EVENT_SYSTEM_MENUPOPUPSTART = 6U,
    /// <summary>Represents the EVENT_SYSTEM_MENUPOPUPEND value.</summary>
    EVENT_SYSTEM_MENUPOPUPEND = 7U,
    /// <summary>Sent when a window takes or releases the capture.</summary>
    EVENT_SYSTEM_CAPTURESTART = 8U,
    /// <summary>Represents the EVENT_SYSTEM_CAPTUREEND value.</summary>
    EVENT_SYSTEM_CAPTUREEND = 9U,
    /// <summary>
    ///     Move Size
    ///     EVENT_SYSTEM_MOVESIZESTART
    ///     EVENT_SYSTEM_MOVESIZEEND
    ///     Sent when a window enters and leaves move-size dragging mode.
    /// </summary>
    EVENT_SYSTEM_MOVESIZESTART = 10U,
    /// <summary>Represents the EVENT_SYSTEM_MOVESIZEEND value.</summary>
    EVENT_SYSTEM_MOVESIZEEND = 11U,
    /// <summary>
    ///     Context Help
    ///     EVENT_SYSTEM_CONTEXTHELPSTART
    ///     EVENT_SYSTEM_CONTEXTHELPEND
    ///     Sent when a window enters and leaves context sensitive help mode.
    /// </summary>
    EVENT_SYSTEM_CONTEXTHELPSTART = 12U,
    /// <summary>Represents the EVENT_SYSTEM_CONTEXTHELPEND value.</summary>
    EVENT_SYSTEM_CONTEXTHELPEND = 13U,
    /// <summary>
    ///     Drag and Drop
    ///     EVENT_SYSTEM_DRAGDROPSTART
    ///     EVENT_SYSTEM_DRAGDROPEND
    ///     Send the START notification just before going into drag and drop loop.  Send
    ///     the END notification just after canceling out.
    ///     Note that it is up to apps and OLE to generate this, since the system
    ///     doesn't know.  Like EVENT_SYSTEM_SOUND, it will be a while before this
    ///     is prevalent.
    /// </summary>
    EVENT_SYSTEM_DRAGDROPSTART = 14U,
    /// <summary>Represents the EVENT_SYSTEM_DRAGDROPEND value.</summary>
    EVENT_SYSTEM_DRAGDROPEND = 15U,
    /// <summary>Represents the EVENT_SYSTEM_DIALOGSTART value.</summary>
    EVENT_SYSTEM_DIALOGSTART = 16U,
    /// <summary>Represents the EVENT_SYSTEM_DIALOGEND value.</summary>
    EVENT_SYSTEM_DIALOGEND = 17U,
    /// <summary>
    ///     EVENT_SYSTEM_SCROLLING
    ///     EVENT_SYSTEM_SCROLLINGSTART
    ///     EVENT_SYSTEM_SCROLLINGEND
    ///     Sent when beginning and ending the tracking of a scrollbar in a window,
    ///     and also for scrollbar controls.
    /// </summary>
    EVENT_SYSTEM_SCROLLINGSTART = 18U,
    /// <summary>Represents the EVENT_SYSTEM_SCROLLINGEND value.</summary>
    EVENT_SYSTEM_SCROLLINGEND = 19U,
    /// <summary>Represents the EVENT_SYSTEM_SWITCHSTART value.</summary>
    EVENT_SYSTEM_SWITCHSTART = 20U,
    /// <summary>Represents the EVENT_SYSTEM_SWITCHEND value.</summary>
    EVENT_SYSTEM_SWITCHEND = 21U,
    /// <summary>Represents the EVENT_SYSTEM_MINIMIZESTART value.</summary>
    EVENT_SYSTEM_MINIMIZESTART = 22U,
    /// <summary>Represents the EVENT_SYSTEM_MINIMIZEEND value.</summary>
    EVENT_SYSTEM_MINIMIZEEND = 23U,
    /// <summary>Represents the EVENT_SYSTEM_DESKTOPSWITCH value.</summary>
    EVENT_SYSTEM_DESKTOPSWITCH = 32U,
    /// <summary>AppGrabbed: HWND = windowHandle of app thumbnail, objectID = 0, childID = 0.</summary>
    EVENT_SYSTEM_SWITCHER_APPGRABBED = 36U,
    /// <summary>Represents the EVENT_SYSTEM_SWITCHER_APPOVERTARGET value.</summary>
    EVENT_SYSTEM_SWITCHER_APPOVERTARGET = 37U,
    /// <summary>Dropped: HWND = windowHandle of app thumbnail, objectID = same, childID = 0.</summary>
    EVENT_SYSTEM_SWITCHER_APPDROPPED = 38U,
    /// <summary>Cancelled: HWND = windowHandle of app thumbnail, objectID = 0, childID = 0.</summary>
    EVENT_SYSTEM_SWITCHER_CANCELLED = 39U,
    /// <summary>
    ///     Sent when an IME's soft key is pressed and should be echoed,
    ///     but is not passed through the keyboard hook.
    ///     Must not be sent when a key is sent through the keyboard hook.
    ///     HWND             is the windowHandle of the UI containing the soft key.
    ///     idChild          is the Unicode value of the character entered.
    ///     idObject         is a bitfield.
    ///     0x00000001: set if a 32-bit Unicode surrogate pair is used.
    /// </summary>
    EVENT_SYSTEM_IME_KEY_NOTIFICATION = 41U,
    /// <summary>Represents the EVENT_SYSTEM_END value.</summary>
    EVENT_SYSTEM_END = 255U,
    /// <summary>Represents the EVENT_OEM_DEFINED_START value.</summary>
    EVENT_OEM_DEFINED_START = 257U,
    /// <summary>Represents the EVENT_OEM_DEFINED_END value.</summary>
    EVENT_OEM_DEFINED_END = 511U,
    /// <summary>Represents the EVENT_CONSOLE_CARET value.</summary>
    EVENT_CONSOLE_CARET = 16_385U,
    /// <summary>Represents the EVENT_CONSOLE_UPDATE_REGION value.</summary>
    EVENT_CONSOLE_UPDATE_REGION = 16_386U,
    /// <summary>Represents the EVENT_CONSOLE_UPDATE_SIMPLE value.</summary>
    EVENT_CONSOLE_UPDATE_SIMPLE = 16_387U,
    /// <summary>Represents the EVENT_CONSOLE_UPDATE_SCROLL value.</summary>
    EVENT_CONSOLE_UPDATE_SCROLL = 16_388U,
    /// <summary>Represents the EVENT_CONSOLE_LAYOUT value.</summary>
    EVENT_CONSOLE_LAYOUT = 16_389U,
    /// <summary>Represents the EVENT_CONSOLE_START_APPLICATION value.</summary>
    EVENT_CONSOLE_START_APPLICATION = 16_390U,
    /// <summary>Represents the EVENT_CONSOLE_END_APPLICATION value.</summary>
    EVENT_CONSOLE_END_APPLICATION = 16_391U,
    /// <summary>Represents the EVENT_UIA_EVENTID_START value.</summary>
    EVENT_UIA_EVENTID_START = 19_968U,
    /// <summary>Represents the EVENT_UIA_EVENTID_END value.</summary>
    EVENT_UIA_EVENTID_END = 20_223U,
    /// <summary>Represents the EVENT_UIA_PROPID_START value.</summary>
    EVENT_UIA_PROPID_START = 29_952U,
    /// <summary>Represents the EVENT_UIA_PROPID_END value.</summary>
    EVENT_UIA_PROPID_END = 30_207U,
    /// <summary>
    ///     Object events
    ///     The system AND apps generate these.  The system generates these for
    ///     real windows.  Apps generate these for objects within their window which
    ///     act like a separate control, e.g. an item in a list view.
    ///     When the system generate them, dwParam2 is always WMOBJID_SELF.  When
    ///     apps generate them, apps put the has-meaning-to-the-app-only ID value
    ///     in dwParam2.
    ///     For all events, if you want detailed accessibility information, callers
    ///     should
    ///     * Call AccessibleObjectFromWindow() with the windowHandle, idObject parameters
    ///     of the event, and IID_IAccessible as the REFIID, to get back an
    ///     IAccessible* to talk to
    ///     * Initialize and fill in a VARIANT as VT_I4 with lVal the idChild
    ///     parameter of the event.
    ///     * If idChild isn't zero, call get_accChild() in the container to see
    ///     if the child is an object in its own right.  If so, you will get
    ///     back an IDispatch* object for the child.  You should release the
    ///     parent, and call QueryInterface() on the child object to get its
    ///     IAccessible*.  Then you talk directly to the child.  Otherwise,
    ///     if get_accChild() returns you nothing, you should continue to
    ///     use the child VARIANT.  You will ask the container for the properties
    ///     of the child identified by the VARIANT.  In other words, the
    ///     child in this case is accessible but not a full-blown object.
    ///     Like a button on a titlebar which is 'small' and has no children.
    ///     For all EVENT_OBJECT events,
    ///     windowHandle is the dude to Send the WM_GETOBJECT message to (unless NULL,
    ///     see above for system things)
    ///     idObject is the ID of the object that can resolve any queries a
    ///     client might have.  It's a way to deal with windowless controls,
    ///     controls that are just drawn on the screen in some larger parent
    ///     window (like SDM), or standard frame elements of a window.
    ///     idChild is the piece inside of the object that is affected.  This
    ///     allows clients to access things that are too small to have full
    ///     blown objects in their own right.  Like the thumb of a scrollbar.
    ///     The windowHandle/idObject pair gets you to the container, the dude you
    ///     probably want to talk to most of the time anyway.  The idChild
    ///     can then be passed into the acc properties to get the name/value
    ///     of it as needed.
    ///     Example #1:
    ///     System propagating a listbox selection change
    ///     EVENT_OBJECT_SELECTION
    ///     windowHandle == listbox windowHandle
    ///     idObject == OBJID_WINDOW
    ///     idChild == new selected item, or CHILDID_SELF if
    ///     nothing now selected within container.
    ///     Word '97 propagating a listbox selection change
    ///     windowHandle == SDM window
    ///     idObject == SDM ID to get at listbox 'control'
    ///     idChild == new selected item, or CHILDID_SELF if
    ///     nothing
    ///     Example #2:
    ///     System propagating a menu item selection on the menu bar
    ///     EVENT_OBJECT_SELECTION
    ///     windowHandle == top level window
    ///     idObject == OBJID_MENU
    ///     idChild == ID of child menu bar item selected
    ///     Example #3:
    ///     System propagating a dropdown coming off of said menu bar item
    ///     EVENT_OBJECT_CREATE
    ///     windowHandle == popup item
    ///     idObject == OBJID_WINDOW
    ///     idChild == CHILDID_SELF
    ///     Example #4:
    ///     For EVENT_OBJECT_REORDER, the object referred to by windowHandle/idObject is the
    ///     PARENT container in which the zorder is occurring.  This is because if
    ///     one child is zordering, all of them are changing their relative zorder.
    /// </summary>
    EVENT_OBJECT_CREATE = 32_768U,
    /// <summary>Represents the EVENT_OBJECT_DESTROY value.</summary>
    EVENT_OBJECT_DESTROY = 32_769U,
    /// <summary>Represents the EVENT_OBJECT_SHOW value.</summary>
    EVENT_OBJECT_SHOW = 32_770U,
    /// <summary>Represents the EVENT_OBJECT_HIDE value.</summary>
    EVENT_OBJECT_HIDE = 32_771U,
    /// <summary>Represents the EVENT_OBJECT_REORDER value.</summary>
    EVENT_OBJECT_REORDER = 32_772U,
    /// <summary>Represents the EVENT_OBJECT_FOCUS value.</summary>
    EVENT_OBJECT_FOCUS = 32_773U,
    /// <summary>
    ///     NOTES:
    ///     There is only one "focused" child item in a parent.  This is the place
    ///     keystrokes are going at a given moment.  Hence only send a notification
    ///     about where the NEW focus is going.  A NEW item getting the focus already
    ///     implies that the OLD item is losing it.
    ///     SELECTION however can be multiple.  Hence the different SELECTION
    ///     notifications.  Here's when to use each:
    ///     (1) Send a SELECTION notification in the simple single selection
    ///     case (like the focus) when the item with the selection is
    ///     merely moving to a different item within a container.  windowHandle + ID
    ///     is the container control, idChildItem is the new child with the
    ///     selection.
    ///     (2) Send a SELECTIONADD notification when a new item has simply been added
    ///     to the selection within a container.  This is appropriate when the
    ///     number of newly selected items is very small.  windowHandle + ID is the
    ///     container control, idChildItem is the new child added to the selection.
    ///     (3) Send a SELECTIONREMOVE notification when a new item has simply been
    ///     removed from the selection within a container.  This is appropriate
    ///     when the number of newly selected items is very small, just like
    ///     SELECTIONADD.  windowHandle + ID is the container control, idChildItem is the
    ///     new child removed from the selection.
    ///     (4) Send a SELECTIONWITHIN notification when the selected items within a
    ///     control have changed substantially.  Rather than propagate a large
    ///     number of changes to reflect removal for some items, addition of
    ///     others, just tell somebody who cares that a lot happened.  It will
    ///     be faster an easier for somebody watching to just turn around and
    ///     query the container control what the new bunch of selected items
    ///     are.
    /// </summary>
    EVENT_OBJECT_SELECTION = 32_774U,
    /// <summary>Represents the EVENT_OBJECT_SELECTIONADD value.</summary>
    EVENT_OBJECT_SELECTIONADD = 32_775U,
    /// <summary>Represents the EVENT_OBJECT_SELECTIONREMOVE value.</summary>
    EVENT_OBJECT_SELECTIONREMOVE = 32_776U,
    /// <summary>Represents the EVENT_OBJECT_SELECTIONWITHIN value.</summary>
    EVENT_OBJECT_SELECTIONWITHIN = 32_777U,
    /// <summary>Represents the EVENT_OBJECT_STATECHANGE value.</summary>
    EVENT_OBJECT_STATECHANGE = 32_778U,
    /// <summary>
    ///     A LOCATIONCHANGE is not sent for every child object when the parent
    ///     changes shape/moves. Send one notification for the topmost object
    ///     that is changing. For example, if the user resizes a top level window,
    ///     USER will generate a LOCATIONCHANGE for it, but not for the menu bar.
    ///     title bar, scrollbars, etc.  that are also changing shape/moving.
    ///     In other words, it only generates LOCATIONCHANGE notifications for
    ///     real windows that are moving/sizing.  It will not generate a LOCATIONCHANGE
    ///     for every non-floating child window when the parent moves (the children are
    ///     logically moving also on screen, but not relative to the parent).
    ///     Now, if the app itself resizes child windows as a result of being
    ///     sized, USER will generate LOCATIONCHANGEs for those dudes also because
    ///     it doesn't know better.
    ///     Note also that USER will generate LOCATIONCHANGE notifications for two
    ///     non-window sys objects:
    ///     (1) System caret.
    ///     (2) Cursor.
    /// </summary>
    EVENT_OBJECT_LOCATIONCHANGE = 32_779U,
    /// <summary>Represents the EVENT_OBJECT_NAMECHANGE value.</summary>
    EVENT_OBJECT_NAMECHANGE = 32_780U,
    /// <summary>Represents the EVENT_OBJECT_DESCRIPTIONCHANGE value.</summary>
    EVENT_OBJECT_DESCRIPTIONCHANGE = 32_781U,
    /// <summary>Represents the EVENT_OBJECT_VALUECHANGE value.</summary>
    EVENT_OBJECT_VALUECHANGE = 32_782U,
    /// <summary>Represents the EVENT_OBJECT_PARENTCHANGE value.</summary>
    EVENT_OBJECT_PARENTCHANGE = 32_783U,
    /// <summary>Represents the EVENT_OBJECT_HELPCHANGE value.</summary>
    EVENT_OBJECT_HELPCHANGE = 32_784U,
    /// <summary>Represents the EVENT_OBJECT_DEFACTIONCHANGE value.</summary>
    EVENT_OBJECT_DEFACTIONCHANGE = 32_785U,
    /// <summary>Represents the EVENT_OBJECT_ACCELERATORCHANGE value.</summary>
    EVENT_OBJECT_ACCELERATORCHANGE = 32_786U,
    /// <summary>Represents the EVENT_OBJECT_INVOKED value.</summary>
    EVENT_OBJECT_INVOKED = 32_787U,
    /// <summary>Represents the EVENT_OBJECT_TEXTSELECTIONCHANGED value.</summary>
    EVENT_OBJECT_TEXTSELECTIONCHANGED = 32_788U,
    /// <summary>
    ///     Sent when ending the scrolling of a window object.
    ///     Unlike the similar event (EVENT_SYSTEM_SCROLLEND), this event is
    ///     associated with the scrolling window itself. There is no difference
    ///     between horizontal or vertical scrolling.
    ///     This event should be posted whenever scroll action is completed, including
    ///     when it is scrolled by scroll bars, mouse wheel, or keyboard navigations.
    ///     example:
    ///     windowHandle == window that is scrolling.
    ///     idObject == OBJID_CLIENT.
    ///     idChild == CHILDID_SELF.
    /// </summary>
    EVENT_OBJECT_CONTENTSCROLLED = 32_789U,
    /// <summary>Represents the EVENT_SYSTEM_ARRANGMENTPREVIEW value.</summary>
    EVENT_SYSTEM_ARRANGMENTPREVIEW = 32_790U,
    /// <summary>
    ///     EVENT_OBJECT_CLOAKED / UNCLOAKED
    ///     Sent when a window is cloaked or uncloaked.
    ///     A cloaked window still exists, but is invisible to
    ///     the user.
    /// </summary>
    EVENT_OBJECT_CLOAKED = 32_791U,
    /// <summary>Represents the EVENT_OBJECT_UNCLOAKED value.</summary>
    EVENT_OBJECT_UNCLOAKED = 32_792U,
    /// <summary>
    ///     EVENT_OBJECT_LIVEREGIONCHANGED
    ///     Sent when an object that is part of a live region
    ///     changes.  A live region is an area of an application
    ///     that changes frequently and/or asynchronously, so
    ///     that an assistive technology tool might want to pay
    ///     special attention to it.
    /// </summary>
    EVENT_OBJECT_LIVEREGIONCHANGED = 32_793U,
    /// <summary>
    ///     EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED
    ///     Sent when a window that is hosting other Accessible
    ///     objects changes the hosted objects.  A client may
    ///     wish to requery to see what the new hosted objects are,
    ///     especially if it has been monitoring events from this
    ///     window.  A hosted object is one with a different Accessibility
    ///     framework (MSAA or UI Automation) from its host.
    ///     Changes in hosted objects with the *same* framework
    ///     as the parent should be handed with the usual structural
    ///     change events, such as EVENT_OBJECT_CREATED for MSAA.
    ///     see above.
    /// </summary>
    EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED = 32_800U,
    /// <summary>
    ///     Drag / Drop Events
    ///     These events are used in conjunction with the
    ///     UI Automation Drag/Drop patterns.
    ///     For DRAGSTART, DRAGCANCEL, and DRAGCOMPLETE,
    ///     HWND+objectID+childID refers to the object being dragged.
    ///     For DRAGENTER, DRAGLEAVE, and DRAGDROPPED,
    ///     HWND+objectID+childID refers to the target of the drop
    ///     that is being hovered over.
    /// </summary>
    EVENT_OBJECT_DRAGSTART = 32_801U,
    /// <summary>Represents the EVENT_OBJECT_DRAGCANCEL value.</summary>
    EVENT_OBJECT_DRAGCANCEL = 32_802U,
    /// <summary>Represents the EVENT_OBJECT_DRAGCOMPLETE value.</summary>
    EVENT_OBJECT_DRAGCOMPLETE = 32_803U,
    /// <summary>Represents the EVENT_OBJECT_DRAGENTER value.</summary>
    EVENT_OBJECT_DRAGENTER = 32_804U,
    /// <summary>Represents the EVENT_OBJECT_DRAGLEAVE value.</summary>
    EVENT_OBJECT_DRAGLEAVE = 32_805U,
    /// <summary>Represents the EVENT_OBJECT_DRAGDROPPED value.</summary>
    EVENT_OBJECT_DRAGDROPPED = 32_806U,
    /// <summary>Represents the EVENT_OBJECT_IME_SHOW value.</summary>
    EVENT_OBJECT_IME_SHOW = 32_807U,
    /// <summary>Represents the EVENT_OBJECT_IME_HIDE value.</summary>
    EVENT_OBJECT_IME_HIDE = 32_808U,
    /// <summary>Represents the EVENT_OBJECT_IME_CHANGE value.</summary>
    EVENT_OBJECT_IME_CHANGE = 32_809U,
    /// <summary>Represents the EVENT_OBJECT_END value.</summary>
    EVENT_OBJECT_END = 33_023U,
    /// <summary>Represents the EVENT_AIA_START value.</summary>
    EVENT_AIA_START = 40_960U,
    /// <summary>Represents the EVENT_AIA_END value.</summary>
    EVENT_AIA_END = 45_055U,
    /// <summary>Represents the EVENT_MAX value.</summary>
    EVENT_MAX = 2_147_483_647U,
}
